name: ${project.name}
version: ${project.version}-b${BUILD_NUMBER}

author: noogotte
website: ${project.url}

main: fr.noogotte.hunger_games.HungerGamePlugin

commands:
    hungergame:
        description: "Main command"
        usage: "<subcommand>"
        aliases: ["hunger"]

    # Game Commands
    "hungergame init":
        description: "Create a new Hunger-Games"
        usage: ""
        permission: "hunger.init"